project:
  type: website
  output-dir: docs

website:
  title: "Kunga's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: project.qmd
        text: project

format:
  html:
    light: lux
    dark: darkly
    fontsize: 12pt

editor: visual

